// Generated from AppConfig::default(). Do not edit this file manually.
import type { AppConfig } from './bindings/AppConfig';

export const DEFAULT_CONFIG: AppConfig = {
  "auto_start": false,
  "setup_completed": false,
  "theme": "system",
  "obs": {
    "host": "",
    "port": 0,
    "password": "",
    "source_name": ""
  },
  "clips_folder": "",
  "stats_folder": "",
  "trim": true,
  "trim_padding_start": 0.0,
  "trim_padding_end": 5.0,
  "delete_after_trimming": false,
  "only_pb": false,
  "cache_version": "",
  "cache_file": "",
  "screenshot": {
    "enabled": false
  },
  "notifications": {
    "enabled": true,
    "urgent_clips": false,
    "failures": true,
    "sound": true
  },
  "ffmpeg": {
    "global_args": "",
    "input_args": "",
    "output_args": ""
  },
  "processes": {
    "scan_interval_secs": 3,
    "paths": {
      "obs": "",
      "kovaaks": "",
      "aimbeast": ""
    }
  },
  "aimbeast": {
    "stats_folder": "",
    "clips_folder": "",
    "obs_source_name": ""
  }
};
