// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AimbeastConfig = { stats_folder: string, clips_folder: string, obs_source_name: string, };
