// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AimbeastConfig } from "./aimbeast-config";
import type { FFmpegConfig } from "./ffmpeg-config";
import type { NotificationsConfig } from "./notifications-config";
import type { ObsConfig } from "./obs-config";
import type { ProcessesConfig } from "./processes-config";
import type { ScreenshotConfig } from "./screenshot-config";
import type { Theme } from "./theme";

export type AppConfig = { auto_start: boolean, 
/**
 * False until the first-run checklist is finished or skipped.
 */
setup_completed: boolean, theme: Theme, obs: ObsConfig, clips_folder: string, stats_folder: string, trim: boolean, trim_padding_start: number, trim_padding_end: number, delete_after_trimming: boolean, only_pb: boolean, cache_version: string, cache_file: string, screenshot: ScreenshotConfig, notifications: NotificationsConfig, ffmpeg: FFmpegConfig, processes: ProcessesConfig, aimbeast: AimbeastConfig, };
