// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three slots of an FFmpeg command line:
 * `ffmpeg [global_args] [input_args] -i input [output_args] output`.
 *
 * Each holds the text the user typed, split by [`crate::args::parse`] when the
 * command is built.
 *
 * These apply to the pass that runs *after* trimming, so they can't interfere
 * with the trim's own options. When all three are empty no second pass runs.
 */
export type FFmpegConfig = { global_args: string, input_args: string, output_args: string, };
