// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The desktop notification shown when a clip has been saved and trimmed.
 *
 * Both default to on: this shipped unconditional, so anyone upgrading keeps
 * the behaviour they already had rather than silently losing it.
 */
export type NotificationsConfig = { enabled: boolean, 
/**
 * Send saved-clip notifications as urgent too, so Do Not Disturb shows
 * them. Off by default: it costs a toast that sits on screen until
 * dismissed, which is a lot to pay per clip when nothing is wrong.
 */
urgent_clips: boolean, 
/**
 * Notify when something goes wrong, not just when a clip lands. Separate
 * from `enabled`: someone who finds a toast per clip noisy may still want
 * to hear that clipping has stopped working.
 */
failures: boolean, sound: boolean, };
