// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessPaths } from "./ProcessPaths";

export type ProcessesConfig = { 
/**
 * Narrower than it needs to be on purpose: u64 maps to a JS bigint in
 * the generated types, and no poll interval needs that range.
 */
scan_interval_secs: number, paths: ProcessPaths, };
