// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which colour scheme the window uses. `System` follows the OS setting.
 */
export type Theme = "system" | "light" | "dark";
